// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failed_events.sql

package db

import (
	"context"
)

const countActiveFailedEvents = `-- name: CountActiveFailedEvents :one
SELECT COUNT(*)::BIGINT FROM failed_events WHERE quarantined_at IS NULL
`

// Refreshes the in-process DLQ depth gauge after each drain pass.
func (q *Queries) CountActiveFailedEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveFailedEvents)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFailedEvent = `-- name: DeleteFailedEvent :exec
DELETE FROM failed_events WHERE id = $1
`

// Removes a row after a successful drain replay.
func (q *Queries) DeleteFailedEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFailedEvent, id)
	return err
}

const incrementFailedEventAttempt = `-- name: IncrementFailedEventAttempt :exec
UPDATE failed_events
SET attempt_count = attempt_count + 1,
    last_attempt_at = NOW(),
    last_error = $2
WHERE id = $1
`

type IncrementFailedEventAttemptParams struct {
	ID        string
	LastError string
}

// Recorded after a drain CH-insert attempt fails. The fresh last_error
// displaces the previous one — only the most recent failure matters for
// triage.
func (q *Queries) IncrementFailedEventAttempt(ctx context.Context, arg IncrementFailedEventAttemptParams) error {
	_, err := q.db.Exec(ctx, incrementFailedEventAttempt, arg.ID, arg.LastError)
	return err
}

const insertFailedEvent = `-- name: InsertFailedEvent :exec

INSERT INTO failed_events (id, batch_payload, last_error)
VALUES ($1, $2, $3)
`

type InsertFailedEventParams struct {
	ID           string
	BatchPayload []byte
	LastError    string
}

// Dead-letter queue for events the flusher couldn't deliver to ClickHouse.
// One row per failed flush, storing the entire validated batch as JSONB so
// the drain goroutine can retry without losing event boundaries.
//
// Drain progress: oldest-first via failed_events_drain_idx (partial WHERE
// quarantined_at IS NULL). After 20 attempts OR 24h age the row quarantines
// and is left alone; a future cmd/maintenance sweep reaps quarantined rows.
// Called by the flusher after a CH insert fails. id is a UUID v7 from
// idgen.New(); batch_payload carries the validated Event slice as JSON; the
// last_error column records the CH error string for forensics.
func (q *Queries) InsertFailedEvent(ctx context.Context, arg InsertFailedEventParams) error {
	_, err := q.db.Exec(ctx, insertFailedEvent, arg.ID, arg.BatchPayload, arg.LastError)
	return err
}

const listFailedEventsForDrain = `-- name: ListFailedEventsForDrain :many
SELECT id, batch_payload, last_error, attempt_count, created_at,
       last_attempt_at, quarantined_at
FROM failed_events
WHERE quarantined_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

// Oldest-first slice for the drain goroutine. The LIMIT is bounded by
// INGEST_DLQ_DRAIN_BATCH_LIMIT so a deep DLQ doesn't starve other work.
func (q *Queries) ListFailedEventsForDrain(ctx context.Context, limit int32) ([]FailedEvent, error) {
	rows, err := q.db.Query(ctx, listFailedEventsForDrain, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailedEvent{}
	for rows.Next() {
		var i FailedEvent
		if err := rows.Scan(
			&i.ID,
			&i.BatchPayload,
			&i.LastError,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.LastAttemptAt,
			&i.QuarantinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarantineFailedEvent = `-- name: QuarantineFailedEvent :exec
UPDATE failed_events
SET quarantined_at = NOW()
WHERE id = $1
  AND quarantined_at IS NULL
`

// Marks a row as accepted-data-loss after the retry budget is exhausted
// (>=20 attempts OR >24h age). The drain index excludes quarantined rows.
func (q *Queries) QuarantineFailedEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, quarantineFailedEvent, id)
	return err
}
