// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID        string
	ProjectID string
	Name      string
	TokenHash string
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Project struct {
	ID        string
	TeamID    string
	Name      string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	CsrfToken string
}

type Team struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type TeamMembership struct {
	TeamID   string
	UserID   string
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID                 string
	Email              string
	PasswordHash       string
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
