// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID             string
	ProjectID      string
	Name           string
	TokenHash      string
	CreatedAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	TokenPlaintext string
}

type OauthAccessToken struct {
	ID        string
	TokenHash string
	ClientID  string
	UserID    string
	ProjectID string
	Scope     string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type OauthClient struct {
	ID           string
	Name         string
	RedirectUris []string
	CreatedAt    pgtype.Timestamptz
}

type OauthCode struct {
	ID                  string
	CodeHash            string
	ClientID            string
	UserID              string
	ProjectID           string
	RedirectUri         string
	Scope               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           pgtype.Timestamptz
	UsedAt              pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type Project struct {
	ID        string
	TeamID    string
	Name      string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	CsrfToken string
}

type Team struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type TeamInvite struct {
	ID         string
	TeamID     string
	CreatedBy  string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	ConsumedBy *string
	CreatedAt  pgtype.Timestamptz
}

type TeamMembership struct {
	TeamID   string
	UserID   string
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID                 string
	Email              string
	PasswordHash       string
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
