// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_access_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredOAuthAccessTokens = `-- name: DeleteExpiredOAuthAccessTokens :execrows
DELETE FROM oauth_access_tokens
WHERE expires_at < NOW()
`

// Called by cmd/maintenance. Sweeps tokens past their expires_at. Revoked-
// but-not-yet-expired rows are deliberately left alone: the 1h TTL means
// they vanish on the next sweep anyway, and keeping them preserves the
// option to surface a revoked-tokens audit view without a schema change.
func (q *Queries) DeleteExpiredOAuthAccessTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthAccessTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveOAuthAccessTokenByHash = `-- name: GetActiveOAuthAccessTokenByHash :one
SELECT id, token_hash, client_id, user_id, project_id, scope,
       expires_at, revoked_at, created_at
FROM oauth_access_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// Active = not revoked AND not expired. The unique partial index on
// (token_hash) WHERE revoked_at IS NULL keeps this on a single index probe.
func (q *Queries) GetActiveOAuthAccessTokenByHash(ctx context.Context, tokenHash string) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, getActiveOAuthAccessTokenByHash, tokenHash)
	var i OauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.ProjectID,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOAuthAccessToken = `-- name: InsertOAuthAccessToken :exec

INSERT INTO oauth_access_tokens (
    id, token_hash, client_id, user_id, project_id, scope, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOAuthAccessTokenParams struct {
	ID        string
	TokenHash string
	ClientID  string
	UserID    string
	ProjectID string
	Scope     string
	ExpiresAt pgtype.Timestamptz
}

// Access tokens: opaque random bytes, only sha256 stored. RequireBearer looks
// the token up by hash and applies the expiry + revocation filters in SQL so
// the index does the work.
func (q *Queries) InsertOAuthAccessToken(ctx context.Context, arg InsertOAuthAccessTokenParams) error {
	_, err := q.db.Exec(ctx, insertOAuthAccessToken,
		arg.ID,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.ProjectID,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}

const listActiveAccessTokensForUser = `-- name: ListActiveAccessTokensForUser :many
SELECT t.id, t.token_hash, t.client_id, t.user_id, t.project_id, t.scope,
       t.expires_at, t.revoked_at, t.created_at,
       c.name AS client_name
FROM oauth_access_tokens t
JOIN oauth_clients c ON c.id = t.client_id
WHERE t.user_id = $1
  AND t.revoked_at IS NULL
  AND t.expires_at > NOW()
ORDER BY t.created_at DESC
`

type ListActiveAccessTokensForUserRow struct {
	ID         string
	TokenHash  string
	ClientID   string
	UserID     string
	ProjectID  string
	Scope      string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ClientName string
}

// Future "connected apps" page. Returns the joinable surface (client name +
// project id + scope + lifecycle timestamps) for the viewer's active grants.
func (q *Queries) ListActiveAccessTokensForUser(ctx context.Context, userID string) ([]ListActiveAccessTokensForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccessTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAccessTokensForUserRow{}
	for rows.Next() {
		var i ListActiveAccessTokensForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.ClientID,
			&i.UserID,
			&i.ProjectID,
			&i.Scope,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthAccessToken = `-- name: RevokeOAuthAccessToken :execrows
UPDATE oauth_access_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthAccessToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthAccessToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
