// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_clients.sql

package db

import (
	"context"
)

const getOAuthClientByID = `-- name: GetOAuthClientByID :one
SELECT id, name, redirect_uris, created_at
FROM oauth_clients
WHERE id = $1
`

func (q *Queries) GetOAuthClientByID(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByID, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const insertOAuthClient = `-- name: InsertOAuthClient :one

INSERT INTO oauth_clients (id, name, redirect_uris)
VALUES ($1, $2, $3)
RETURNING id, name, redirect_uris, created_at
`

type InsertOAuthClientParams struct {
	ID           string
	Name         string
	RedirectUris []string
}

// OAuth client registry: minimal RFC 7591 surface. Public clients only (no
// client_secret), so the row carries only the identity + the redirect-URI
// allowlist. Redirect URIs are matched exactly at /oauth/authorize; the
// application layer applies the additional scheme/host rules (HTTPS or
// localhost) at registration time.
func (q *Queries) InsertOAuthClient(ctx context.Context, arg InsertOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, insertOAuthClient, arg.ID, arg.Name, arg.RedirectUris)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}
