// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthCode = `-- name: ConsumeOAuthCode :one
UPDATE oauth_codes
SET used_at = NOW()
WHERE code_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
RETURNING id, code_hash, client_id, user_id, project_id,
          redirect_uri, scope, code_challenge, code_challenge_method,
          expires_at, used_at, created_at
`

// One-shot enforcement: succeeds only when used_at IS NULL AND expires_at >
// NOW(); a second call against the same code returns pgx.ErrNoRows, which the
// handler translates to invalid_grant.
func (q *Queries) ConsumeOAuthCode(ctx context.Context, codeHash string) (OauthCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.ProjectID,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOAuthCode = `-- name: InsertOAuthCode :exec

INSERT INTO oauth_codes (
    id, code_hash, client_id, user_id, project_id,
    redirect_uri, scope, code_challenge, code_challenge_method, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertOAuthCodeParams struct {
	ID                  string
	CodeHash            string
	ClientID            string
	UserID              string
	ProjectID           string
	RedirectUri         string
	Scope               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           pgtype.Timestamptz
}

// Authorization codes: short-lived (10 min), one-shot. ConsumeCode runs inside
// a transaction with the access-token insert so a parallel /oauth/token call
// can never double-spend the code (the UPDATE filters used_at IS NULL).
func (q *Queries) InsertOAuthCode(ctx context.Context, arg InsertOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, insertOAuthCode,
		arg.ID,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.ProjectID,
		arg.RedirectUri,
		arg.Scope,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	return err
}
