// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveOAuthCodeByHash = `-- name: GetActiveOAuthCodeByHash :one
SELECT id, code_hash, client_id, user_id, project_id,
       redirect_uri, scope, code_challenge, code_challenge_method,
       expires_at, used_at, created_at
FROM oauth_codes
WHERE code_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

// Read-side of the lookup-then-update. Returns the live row (not used, not
// expired) so the caller can validate client_id / redirect_uri / PKCE before
// committing the consume. pgx.ErrNoRows means unknown / expired / already
// used — all collapse to invalid_grant at the handler.
func (q *Queries) GetActiveOAuthCodeByHash(ctx context.Context, codeHash string) (OauthCode, error) {
	row := q.db.QueryRow(ctx, getActiveOAuthCodeByHash, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.ProjectID,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOAuthCode = `-- name: InsertOAuthCode :exec

INSERT INTO oauth_codes (
    id, code_hash, client_id, user_id, project_id,
    redirect_uri, scope, code_challenge, code_challenge_method, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertOAuthCodeParams struct {
	ID                  string
	CodeHash            string
	ClientID            string
	UserID              string
	ProjectID           string
	RedirectUri         string
	Scope               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           pgtype.Timestamptz
}

// Authorization codes: short-lived (10 min), one-shot. Consumption is a
// two-step lookup-then-update so the application layer can validate the
// bound (client_id, redirect_uri, PKCE) tuple BEFORE the row is burnt — a
// failed PKCE check leaves the code intact for a legitimate retry rather
// than forcing the user back through /oauth/authorize. One-shot is still
// enforced by MarkOAuthCodeUsed's `WHERE used_at IS NULL`: a concurrent
// /oauth/token call racing on the same row produces RowsAffected == 0 on
// the loser, which the handler maps to invalid_grant.
//
// expires_at filtering happens in SQL on the lookup so the partial index
// continues to do the work; the application never sees expired rows.
//
// This file pairs with internal/oauth/codes.go.
func (q *Queries) InsertOAuthCode(ctx context.Context, arg InsertOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, insertOAuthCode,
		arg.ID,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.ProjectID,
		arg.RedirectUri,
		arg.Scope,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	return err
}

const markOAuthCodeUsed = `-- name: MarkOAuthCodeUsed :execrows
UPDATE oauth_codes
SET used_at = NOW()
WHERE id = $1
  AND used_at IS NULL
`

// Write-side of the lookup-then-update. The `used_at IS NULL` predicate is
// the one-shot guard: a parallel /oauth/token call that also validated the
// same code races on this UPDATE; exactly one row is touched and the loser
// sees RowsAffected == 0.
func (q *Queries) MarkOAuthCodeUsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markOAuthCodeUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
