// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
)

const createProjectForUser = `-- name: CreateProjectForUser :one
INSERT INTO projects (id, team_id, name)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1 FROM team_memberships
    WHERE team_id = $2 AND user_id = $4
)
RETURNING id, team_id, name, created_at, deleted_at
`

type CreateProjectForUserParams struct {
	ID     string
	TeamID string
	Name   string
	UserID string
}

// The WHERE EXISTS guard makes the INSERT a no-op when the caller is not a
// member of the target team. RowsAffected == 0 → auth.ErrNotVisible.
func (q *Queries) CreateProjectForUser(ctx context.Context, arg CreateProjectForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProjectForUser,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one

SELECT p.id, p.team_id, p.name, p.created_at, p.deleted_at
FROM projects p
JOIN team_memberships tm ON tm.team_id = p.team_id
WHERE p.id = $1
  AND tm.user_id = $2
  AND p.deleted_at IS NULL
`

type GetProjectForUserParams struct {
	ID     string
	UserID string
}

// All project queries are membership-gated via a JOIN on team_memberships.
// A row that doesn't belong to a team the viewer is in returns zero rows,
// which the viewer translates to auth.ErrNotVisible (Issue 6).
// Soft-deleted rows (deleted_at IS NOT NULL) are excluded from every read.
func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsForTeamForUser = `-- name: ListProjectsForTeamForUser :many
SELECT p.id, p.team_id, p.name, p.created_at, p.deleted_at
FROM projects p
JOIN team_memberships tm ON tm.team_id = p.team_id
WHERE p.team_id = $1
  AND tm.user_id = $2
  AND p.deleted_at IS NULL
ORDER BY p.created_at ASC
`

type ListProjectsForTeamForUserParams struct {
	TeamID string
	UserID string
}

func (q *Queries) ListProjectsForTeamForUser(ctx context.Context, arg ListProjectsForTeamForUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForTeamForUser, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForTeamsForUser = `-- name: ListProjectsForTeamsForUser :many
SELECT p.id, p.team_id, p.name, p.created_at, p.deleted_at
FROM projects p
JOIN team_memberships tm ON tm.team_id = p.team_id
WHERE p.team_id = ANY($1::uuid[])
  AND tm.user_id = $2
  AND p.deleted_at IS NULL
ORDER BY p.team_id ASC, p.created_at ASC
`

type ListProjectsForTeamsForUserParams struct {
	Column1 []string
	UserID  string
}

// Used by the rebuilt home page (Issue 15): bounded 2-query pattern.
func (q *Queries) ListProjectsForTeamsForUser(ctx context.Context, arg ListProjectsForTeamsForUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForTeamsForUser, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProjectForUser = `-- name: SoftDeleteProjectForUser :execrows
UPDATE projects
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND team_id IN (
      SELECT team_id FROM team_memberships WHERE user_id = $2
  )
`

type SoftDeleteProjectForUserParams struct {
	ID     string
	UserID string
}

// Returns RowsAffected; 0 means either not-a-member or already-deleted, both
// of which collapse to ErrNotVisible at the viewer.
func (q *Queries) SoftDeleteProjectForUser(ctx context.Context, arg SoftDeleteProjectForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProjectForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
