// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at, csrf_token)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, expires_at, csrf_token, created_at
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CsrfToken string
}

type CreateSessionRow struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CsrfToken string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CsrfToken,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CsrfToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.id                    AS session_id,
    s.user_id               AS user_id,
    s.expires_at            AS expires_at,
    s.csrf_token            AS csrf_token,
    s.created_at            AS created_at,
    u.email                 AS user_email,
    u.must_change_password  AS must_change_password
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
`

type GetSessionWithUserRow struct {
	SessionID          string
	UserID             string
	ExpiresAt          pgtype.Timestamptz
	CsrfToken          string
	CreatedAt          pgtype.Timestamptz
	UserEmail          string
	MustChangePassword bool
}

func (q *Queries) GetSessionWithUser(ctx context.Context, id string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, id)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.UserEmail,
		&i.MustChangePassword,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET expires_at = $2
WHERE id = $1
`

type TouchSessionParams struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
