// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInviteByHash = `-- name: ConsumeInviteByHash :one
UPDATE team_invites
SET consumed_at = NOW(),
    consumed_by = $2
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING id, team_id, created_by, token_hash, expires_at, consumed_at, consumed_by, created_at
`

type ConsumeInviteByHashParams struct {
	TokenHash  string
	ConsumedBy *string
}

// Atomic burn. RowsAffected via RETURNING — if 0 rows, the invite was
// consumed, expired, or never existed; caller maps all three to 404.
func (q *Queries) ConsumeInviteByHash(ctx context.Context, arg ConsumeInviteByHashParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, consumeInviteByHash, arg.TokenHash, arg.ConsumedBy)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamInviteForUser = `-- name: CreateTeamInviteForUser :one

INSERT INTO team_invites (id, team_id, created_by, token_hash, expires_at)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (
    SELECT 1 FROM team_memberships
    WHERE team_id = $2 AND user_id = $3
)
RETURNING id, team_id, created_by, token_hash, expires_at, consumed_at, consumed_by, created_at
`

type CreateTeamInviteForUserParams struct {
	ID        string
	TeamID    string
	CreatedBy string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// Invite tokens follow the same shape as api_tokens: plaintext shared via the
// URL only, sha256 hex persisted. Consume is a single atomic UPDATE so two
// concurrent claimants can never both succeed (Issue 14 race test).
// Membership-gated: caller must be in the team they're inviting into.
func (q *Queries) CreateTeamInviteForUser(ctx context.Context, arg CreateTeamInviteForUserParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, createTeamInviteForUser,
		arg.ID,
		arg.TeamID,
		arg.CreatedBy,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveInviteByHash = `-- name: GetActiveInviteByHash :one
SELECT i.id, i.team_id, i.created_by, i.token_hash, i.expires_at,
       i.consumed_at, i.consumed_by, i.created_at,
       t.name AS team_name
FROM team_invites i
JOIN teams t ON t.id = i.team_id
WHERE i.token_hash = $1
  AND i.consumed_at IS NULL
  AND i.expires_at > NOW()
`

type GetActiveInviteByHashRow struct {
	ID         string
	TeamID     string
	CreatedBy  string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	ConsumedBy *string
	CreatedAt  pgtype.Timestamptz
	TeamName   string
}

// Used by the GET /invites/:t confirmation page; expired or consumed → no row.
func (q *Queries) GetActiveInviteByHash(ctx context.Context, tokenHash string) (GetActiveInviteByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveInviteByHash, tokenHash)
	var i GetActiveInviteByHashRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.CreatedAt,
		&i.TeamName,
	)
	return i, err
}
