// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateTeamParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTeamMembership = `-- name: CreateTeamMembership :exec
INSERT INTO team_memberships (team_id, user_id)
VALUES ($1, $2)
`

type CreateTeamMembershipParams struct {
	TeamID string
	UserID string
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) error {
	_, err := q.db.Exec(ctx, createTeamMembership, arg.TeamID, arg.UserID)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, created_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT t.id, t.name, t.created_at
FROM teams t
JOIN team_memberships tm ON tm.team_id = t.id
WHERE tm.user_id = $1
ORDER BY t.created_at ASC
`

func (q *Queries) ListTeamsForUser(ctx context.Context, userID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
